### ISSUE TITLE
RayCluster automatic connection

### ISSUE THREAD

**Issue by al-rigazzi** [CrayLabs/SmartSim#102]
# Description
Currently, a user who sets up a Ray cluster through `RayCluster` has to call `ray.init` to start communicating with it. This requires the user to know:
- The head node address and Ray port: this can be retrieved through `RayCluster` with `head_address`
- Whether the head node is on the same host where the connection is required: this is something the user has to know, as the initialization of Ray is quite different in this case (requires the password, and the address does not start with `ray://`.

Since we can easily get the needed info, adding a `connect` method to `RayCluster` would make things easier for users. SmartSim will automatically setup the correct connection to the cluster and the user will be able to run the same script, no matter what the setup is.

# Justification
It is a helper function which will make things easier for users.

# Implementation Strategy
What is needed is a function `RayCluster.connect()` which checks Ray head's and the current host IP, sets up the connection, and the  returns a context or a dictionary, depending what Ray initialization is required.

**Comment by mellis13** [comment]
Closing since issue #227 will drop ray support.
