### ISSUE TITLE
Add support for SGE (Sun Grid Engine)

### ISSUE THREAD

**Issue by al-rigazzi** [CrayLabs/SmartSim#117]
# Description
Add SGE integration to SmartSim.

# Justification
Sun Grid Engine (SGE) is a workload manager (WLM) used on clusters and supercomputers. Integrating SGE, we would allow its users to adopt SmartSim for their workloads. 

# Implementation Strategy
- [ ] Add `Settings` and `BatchSettings` for SGE
- [ ] Add `Orchestrator`
- [ ] Test implementation on SGE systems

**Comment by thoth291** [comment]
I can help you with testing. We have isolated test cluster with SGE enabled there.
Also if you have any questions on how to submit jobs in SGE - I can help you with that too.
