### ISSUE TITLE
Change the way environmental variables are passed (batch mode)

### ISSUE THREAD

**Issue by hubert-chrzaniuk-gc** [CrayLabs/SmartSim#128]
# Description
When in batch mode SmartSim creates the batch script then executed on target machine. Each generated srun execution in the script overwrites PATH, LD_LIBRARY_PATH and PYTHONPATH using export parameter of srun. This can be inconvenient if added preamble (using add_premable function) wishes to modify one of those since the result will never propagate to the target machine.

# Justification
Some use-cases require sourcing scripts before using specialised hardware. Those scripts often tend to modify above environmental variables. Generally user should be able to change those in preamble.

# Implementation Strategy
PATH, LD_LIBRARY_PATH and PYTHONPATH should not be changed by using export parameter of srun but rather in one of two following ways: 

1. Adding export option to generated SBATCH script : _#SBATCH --export_ and removing export from srun parameters of generated script. Srun will propagate those and the user will have a chance to add additional paths.
2. Simply modifying those variables as a part of sbatch script by adding _export PATH=$PATH:smartsim_paths...._ to the script after preamble.

This should not change the way SmartSim works while giving the user more flexibility on preamble scripts.

**Comment by Spartee** [comment]
This is a great suggestion. Should also clean up the ``srun`` calls themselves. I think this was done more as a convenience in the beginning and shouldn't be necessary, although further investigation is needed. The slurm environment variables can cause some unexpected issues esp when running on ``--no-shell`` allocations. 

I would like to propose we incorporate this by introducing environment control for all the batch settings. Currently we don't offer much here and I think this would benefit users like @hubert-chrzaniuk-gc. 

### Tentative changes/additions (possibly separate tickets)

- [ ] Remove preset env vars from ``SrunSettings``. 

Ensure we can do without specification here. If these were added for convenience and they are being inconvenient then I vote we take them out. If the slurm test suite does not pass without specification then I think the 2nd option above should work as well. Either way, this can go in quickly so we can unblock @hubert-chrzaniuk-gc 

Option 1 won't work (per my understanding of your description) as we often have users specify different environment variables for multiple jobs within a batch, hence we need those ``--export`` flags.

- [ ] Add top level flag for batch environment passing control.

This would look like a flag:  ``BatchSettings.pass_env``. For slurm, the default would be ``False`` implying that only the Slurm environment variables and the user/smartsim passed environment variables would be passed to the batch script. For PBS this would be controlling the ``-V`` flag. 

- [ ] Use flag in ``<launcher>Step._write_script`` to determine environment settings and write the appropriate value.

We may think about expanding ``BatchSettings`` to handle user provided environment variables in the future (in addition to ``RunSettings``.


@al-rigazzi thoughts here? git's telling me you know more about this than I do. Am I wrong in thinking that we don't need those presets anymore? I'm thinking this was put in before all of the path expansion work that we did. 

thanks @hubert-chrzaniuk-gc !

**Comment by al-rigazzi** [comment]
@Spartee I agree, I think the presets are legacy code we can safely remove or handle differently. I think that option should be viable.

**Comment by hubert-chrzaniuk-gc** [comment]
Thanks guys ! Looking forward to the change.

**Comment by ben-albrecht** [comment]
Hi @hubert-chrzaniuk-gc, we no longer set these env vars as of #181. If you're working off of git repository, you can try these changes out. Otherwise, they will be in the next release.

Thanks again for bringing this to our attention.

**Comment by hubert-chrzaniuk-gc** [comment]
Thanks @ben-albrecht0 it looks great ! I will try to test this out, it is possible that it will not happen before next release. Anyway, I was looking into the code, and this seems to be all we needed - this will make SmartSim and IPU integration much easier.
