### ISSUE TITLE
Experiment API Test Revision

### ISSUE THREAD

**Issue by amandarichardsonn** [CrayLabs/SmartSim#226]
# Description
The experiment.py file needs to be revised to match the Job API tand Experiment Job API tests. The experiment.py file needs to be split into multiple files with additional helper methods added.

# Justification
We need to achieve a high level of organization and code quality with all of our tests. Therefore, we should sink the experiment.py file to match the related test files.

# Implementation Strategy
- Divide code by get, update, list, delete, me, create
- Add helper methods to each file
- Remove excess code
- Update style to conform with style requirements (experiment + job)

**Comment by mellis13** [comment]
Duplicate.
