### ISSUE TITLE
Export existing environment using Slurm

### ISSUE THREAD

**Issue by iakovos-panourgias** [CrayLabs/SmartSim#257]
# Description
The function `update_env()` is used to create a list of environment variables which are used with the `--export` option of srun. Unfortunately, when `--export` is used; the propagated environment will only contain the variables that we specified in the `--export` option (and the SLURM_* environment variables).

The usecase where a user wants to use his existing environment and **append** a few environment variables is not handled. Slurm supports the keyword `ALL`; however, `ALL` can't be used with `update_env()` because it's unique and `update_env()` accepts tuples of variables.

Using `add_exe_args()` doesn't work either; because it adds a second `--export` directive for srun.

If you think this is a Feature; please feel free to change it from a bug to a feature.

# How to reproduce
Running SmartSim-Scaling fails with dynamically linked libraries not found (due to the missing LD_LIBRARY_PATH varaible).

# Expected behavior
The user's environment should be appended with any new SmartSim specific variables.

A **hack** (that I am using to successfully run experiments) is the following (in file `smartsim/_core/launcher/step/slurmStep.py`): 
```shell

-                cmd += ["--export", env_var_str]
+                cmd += ["--export ALL,", env_var_str]

```

# System
 - OS: Red Hat Enterprise Linux release 
 - OS version: 8.4 (Ootpa)
 - Commit/version of library: v0.4.1
 - Workload manager (e.g. PBS, Slurm): Slurm
 - Workload manager version: 21.08.8-2

**Comment by al-rigazzi** [comment]
Hi @iakovos-panourgias! Thanks for catching this and finding the fix! We noticed this is happening on some systems, and it seems to be due to a change in how Slurm handles environment variables. We are going to address this and let you know when it is implemented.
