### ISSUE TITLE
Reduce SmartSim orchestrator instantiations in unit tests

### ISSUE THREAD

**Issue by ankona** [CrayLabs/SmartSim#296]
# Description
In order to reduce the duration of test cycles in smartsim, we should investigate reusing a shared orchestrator across tests where possible. In addition, we may consider avoiding using the same port to avoid collisions.

# Justification
Development team should benefit from a reduction in unit test run times.

# Implementation Strategy
- Identify all unit tests that do not uniquely test orchestrator startup/shutdown features.
- Add shared orchestrator in startup
- Add shared orchestrator destruction in test shutdown
- Modify tests to attach to shared orchestrator where possible

**Comment by mellis13** [comment]
@mellis13 Add to the user/dev pain points for next release.
