### ISSUE TITLE
Ensemble key prefix

### ISSUE THREAD

**Issue by b-fg** [CrayLabs/SmartSim#299]
When using an ensemble of models, the automatic key prefixing is not mentioned in the [docs](https://www.craylabs.org/docs/experiment.html#ensemble), or at least I could not find it. I thought `enable_key_prefixing` would prefix name and model ID to the read/write operations, but only does the name (as stated in docs).
It would be great to clarify in the docs if possible :)

**Comment by mellis13** [comment]
This is great feedback!  We will work on improving the documentation for ensembles.  Let us know if you hit any blockers in the meantime.

**Comment by mellis13** [comment]
This feedback was incorporated into PR #322 and merged into develop.  The new documentation is available at https://www.craylabs.org/develop/experiment.html#prefixing-keys-in-the-orchestrator .  I'll close this issue, but please let us know if you have any other feedback.
