### ISSUE TITLE
Launch colo in SmartSim

### ISSUE THREAD

**Issue by amandarichardsonn** [CrayLabs/SmartSim#340]
# Description
To launch a colocated scaling test, the app and database are launched separately from a `.colocated_launcher.sh` file created after a scaling test is invoked. In the `.colocated_launcher.sh`, we launch the redis-server and the app in parallel shown in the example below. This leads to the app requesting scripts or models from the redis-server before it is fully finished.

`redis-server &
$@`

# Justification
Since we are launching the redis-server and the app at the same time via the `.colocated_launcher.sh` file, the app can request the model or script before they are finished uploading resulting in an error. We can avoid this issue by implementing the `poll_model` and `poll_script` SmartSim methods that continually check for the script and model to exists before continuing. However, we should not make the user implement these methods. We should rather add colocated launching functionality where the app does not start until the model and script has fully loaded. This is already implemented for standard deployment.

# Check list
- [ ] SmartSim supports colocated deployment instead of manually deploying in the scaling test file directory
- [ ] The app does not launch before the script and model have finished uploading

**Comment by mellis13** [comment]
@amandarichardsonn Let's change from epic to ticket and also add/improve content as discussed.
