### ISSUE TITLE
Spack Install

### ISSUE THREAD

**Issue by Spartee** [CrayLabs/SmartSim#39]
# Description
Create an automated Spack install for SmartSim.

# Justification
SmartSim has three external dependencies that could be installed by Spack. Hiredis and Redis are already a part of the Spack ecosystem, but will need to be updated as they only provide redis < 5.0.3 and hiredis < 1.0.0. This should be fairly straightforward as spack allows users to pull from Github similar to how we do in our  ``Makefile``

# Implementation Strategy

This involves
 - Installing python lib to a python environment with dependencies
 - Installing Redis, RedisAI (what ``smart --device gpu/cpu`` currently does)
 - Possibly also installing SmartRedis (C/C++/Fortran lib) depending on which Spack install gets implemented first.

**Comment by MattToast** [comment]
SmartSim v0.5.0 is now available as a spack package under the name `py-smartsim`
