### ISSUE TITLE
Upload codecov results only once per CI/CD run

### ISSUE THREAD

**Issue by al-rigazzi** [CrayLabs/SmartSim#393]
# Description
We should find a way to upload codecov results only for one workflow in our GitHub CI/CD. 

# Justification
Every GitHub workflow in our CI/CD uploads results to codecov. This introduces instability in the test results, as it seems that the codecov server sometimes refuses the connection. If we uploaded the results only in one workflow of our matrix, we could mitigate this issue.

# Implementation Strategy
The action to upload codecov results should only be performed for one combination in our test matrix. It would be great if we could identify "the first combination" dynamically, and not link this action to a hard-coded matrix entry. This would make sure the action will always be performed once, even if the matrix changes.

**Comment by mellis13** [comment]
@al-rigazzi per group discussion, let's rewrite to continue on codecov failure

**Comment by mellis13** [comment]
We made failures of codecov not cause failure of the github action.  Closing this as done.
