### ISSUE TITLE
 PytorchStreamReader fails to find file

### ISSUE THREAD

**Issue by syedalihasany** [CrayLabs/SmartSim#405]
# Description
I have a ML model "ali_model.pt" which I want to execute from a C++ program using the smartsim client. The orchestrator and database is started from the python interpreter with launcher specified as "local" and port specified as "6379". Then I run the C++ program which starts the client with localhost:6379 but gives the following error:

terminate called after throwing an instance of 'SmartRedis::RuntimeException'
  what():  Redis error when executing command: PytorchStreamReader failed locating file constants.pkl: file not found Exception raised from valid at ../caffe2/serialize/inline_container.cc:158 (most recent call first): frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x42 (0x7f6f88345f72 in /home/bohan/.local/lib/python3.8/site-packages/smartsim/_core/lib/backends/redisai_torch/lib/libc10.so) frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x5b (0x7f6f883425eb in /home/bohan/.local/lib/python3.8/site-packages/smartsim/_core/lib/backends/redisai_torch/lib/libc10.so) frame #2: caffe2::serialize::PyTorchStreamReader::valid(char const*, char const*) + 0x8e (0x7f6f6d77328e in /home/bohan/.local/lib/python3.8/site-packages/smartsim/_core/lib/backends/redisai_torch/lib/libtorch_cpu.so) frame #3: caffe2::serialize::PyTorchStreamReader::getRecordID(std::string const&) + 0x47 (0x7f6f6d773457 in /home/bohan/.local/lib/python3.8/site-packages/smartsim/_core/lib/backends/redisai_torch/lib/libtorch_cpu.so) frame #4: caffe2::serialize::PyTorchStreamReader::getRecord(std::string const&) + 0x45 (0x7f6f6d773525 in /home/bohan/.local/lib/python3.8/site-packages/smartsim/_core/lib/backends/redisai_torch/lib/libtorch_cpu.so) frame #5: torch::jit::readArchiveAndTensors(std::string const&, std::string const&, std::string const&, c10::optional<std::function<c10::StrongTypePtr (c10::QualifiedName const&)> >, c10::optional<std::function<c10::intrusive_ptr<c10::ivalue::Object, c10::detail::intrusive_target_default_null_type<c10::ivalue::Object> > (c10::StrongTypePtr, c10::IValue)> >, c10::optional<c10::Device>, caffe2::serialize::PyTorchStreamReader&, c10::Type::SingletonOrSharedTypePtr<c10::Type> (*)(std::string const&), std::shared_ptr<torch::jit::DeserializationStorageContext>) + 0xac (0x7f6f6e2f41ec in /home/bohan/.local/lib/python3.8/site-packages/smartsim/_core/lib/backends/redisai_torch/lib/libtorch_cpu.so) frame #6: <unknown function> + 0x32f81f9 (0x7f6f6e2ee1f9 in /home/bohan/.local/lib/python3.8/site-packages/smartsim/_core/lib/backends/redisai_torch/lib/libtorch_cpu.so) frame #7: <unknown function> + 0x32f9eaf (0x7f6f6e2efeaf in /home/bohan/.local/lib/python3.8/site-packages/smartsim/_core/lib/backends/redisai_torch/lib/libtorch_cpu.so) frame #8: torch::jit::load(std::shared_ptr<caffe2::serialize::ReadAdapterInterface>, c10::optional<c10::Device>, std::unordered_map<std::string, std::string, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, std::string> > >&) + 0x1af (0x7f6f6e2f124f in /home/bohan/.local/lib/python3.8/site-packages/smartsim/_core/lib/backends/redisai_torch/lib/libtorch_cpu.so) frame #9: torch::jit::load(std::istream&, c10::optional<c10::Device>, std::unordered_map<std::string, std::string, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, std::string> > >&) + 0xad (0x7f6f6e2f2d8d in /home/bohan/.local/lib/python3.8/site-packages/smartsim/_core/lib/backends/redisai_torch/lib/libtorch_cpu.so) frame #10: torch::jit::load(std::istream&, c10::optional<c10::Device>) + 0x54 (0x7f6f6e2f2e64 in /home/bohan/.local/lib/python3.8/site-packages/smartsim/_core/lib/backends/redisai_torch/lib/libtorch_cpu.so) frame #11: torchLoadModel + 0x211 (0x7f6f883bbe11 in /home/bohan/.local/lib/python3.8/site-packages/smartsim/_core/lib/backends/redisai_torch/redisai_torch.so) frame #12: RAI_ModelCreateTorch + 0xd2 (0x7f6f883b2b52 in /home/bohan/.local/lib/python3.8/site-packages/smartsim/_core/lib/backends/redisai_torch/redisai_torch.so) frame #13: RAI_ModelCreate + 0x1de (0x7f6f8ac0905e in /home/bohan/.local/lib/python3.8/site-packages/smartsim/_core/lib) frame #14: RedisAI_ModelStore_RedisCommand + 0x9eb (0x7f6f8abf7fdb in /home/bohan/.local/lib/python3.8/site-packages/smartsim/_core/lib) frame #15: RedisModuleCommandDispatcher + 0x4c (0x555f89db383c in /home/bohan/.local/lib/python3.8/site-packages/smartsim/_core/bin/redis-server 127.0.0.1:6379) frame #16: call + 0xdf (0x555f89d15e1f in /home/bohan/.local/lib/python3.8/site-packages/smartsim/_core/bin/redis-server 127.0.0.1:6379) frame #17: processCommand + 0x8dd (0x555f89d1869d in /home/bohan/.local/lib/python3.8/site-packages/smartsim/_core/bin/redis-server 127.0.0.1:6379) frame #18: processCommandAndResetClient + 0x20 (0x555f89d2e6c0 in /home/bohan/.local/lib/python3.8/site-packages/smartsim/_core/bin/redis-server 127.0.0.1:6379) frame #19: processInputBuffer + 0xd8 (0x555f89d31488 in /home/bohan/.local/lib/python3.8/site-packages/smartsim/_core/bin/redis-server 127.0.0.1:6379) frame #20: readQueryFromClient + 0x2e8 (0x555f89d34c68 in /home/bohan/.local/lib/python3.8/site-packages/smartsim/_core/bin/redis-server 127.0.0.1:6379) frame #21: <unknown function> + 0x13262c (0x555f89ddb62c in /home/bohan/.local/lib/python3.8/site-packages/smartsim/_core/bin/redis-server 127.0.0.1:6379) frame #22: aeProcessEvents + 0x1ea (0x555f89d0cdda in /home/bohan/.local/lib/python3.8/site-packages/smartsim/_core/bin/redis-server 127.0.0.1:6379) frame #23: aeMain + 0x1d (0x555f89d0d19d in /home/bohan/.local/lib/python3.8/site-packages/smartsim/_core/bin/redis-server 127.0.0.1:6379) frame #24: main + 0x32d (0x555f89d08d2d in /home/bohan/.local/lib/python3.8/site-packages/smartsim/_core/bin/redis-server 127.0.0.1:6379) frame #25: __libc_start_main + 0xf3 (0x7f6f8b141083 in /lib/x86_64-linux-gnu/libc.so.6) frame #26: _start + 0x2e (0x555f89d0935e in /home/bohan/.local/lib/python3.8/site-packages/smartsim/_core/bin/redis-server 127.0.0.1:6379) 
Aborted (core dumped)

# How to reproduce
snippet of the python command used to start the database:
```
>>> exp = Experiment("MyExample", launcher='local')
>>> db = Orchestrator()
>>> exp.start(db)
```

snippet of the C++ code that I execute after the exp.start(db) python command:

```
    bool cluster_mode = false; // Set to false if not using a clustered database
    SmartRedis::Client client(cluster_mode, __FILE__);
    std::cout<<"set client"<<std::endl;

    // Use the client to set a model in the database from a file
    std::string model_key = "ali_model";
    std::string model_file = "../ali_model.pt";
    std::cout<<"USING CPU"<<std::endl;
    client.set_model_from_file(model_key, model_file, "TORCH", "CPU",1000); 
    std::cout<<"set model"<<std::endl;
```

# System
 - OS: Ubuntu
 - OS version: 20.04.6
 - Commit/version of library:
 - Workload manager (e.g. PBS, Slurm):
 - Workload manager version:

**Comment by al-rigazzi** [comment]
Hi @syedalihasany,

from what I read in [this PyTorch post](https://discuss.pytorch.org/t/pytorchstreamreader-failed-locating-file-constants-pkl-file-not-found/169884) it appears the problem might be that you are trying to upload a model which has not been jit-traced or jit-scripted. 

Is `ali_model.pt` a plain PyTorch model? In that case, you may want to follow what [this tutorial](https://pytorch.org/tutorials/advanced/cpp_export.html#converting-to-torch-script-via-tracing) and jit-trace your model. Once you have the file of the jit-traced model, you should be able to upload it to the `Orchestrator`.

Can you try this and let me know if it works? Thanks!

**Comment by syedalihasany** [comment]
Hi Al,

Thanks for getting back to me so quickly. I will try this and let you know
what I find.

Thanks again for your help!

Yours sincerely,
Ali

**Comment by syedalihasany** [comment]
Tracing and saving the model as a jit script worked
