### ISSUE TITLE
`smart teardown --dragon` does not remove shared memory segments

### ISSUE THREAD

**Issue by al-rigazzi** [CrayLabs/SmartSim#612]
# Description
The current `smart teardown --dragon` does not clean up the `/dev/shmem` segments.

# How to reproduce
Interrupt a running Dragon-based example which reserved shared memory segments and try to run `smart teardown --dragon`. The segments will not be cleared. 

One possible explanation is that the teardown command is killed by `dragon-cleanup` before it gets to the shmem-related section of the `dragon-cleanup` script itself.

# Expected behavior
The shared memory segments should be cleaned up.

# System
 - Commit/version of library: 0.7.0
 - Workload manager (e.g. PBS, Slurm): Slurm+Dragon

**Comment by ankona** [comment]
[Added PR](https://github.hpe.com/hpe/hpc-pe-dragon-dragon/pull/711/files) to dragon repo fixing the early termination of any python processes tied to `dragon-cleanup`
