### ISSUE TITLE
Typo on page /tutorials/ml_inference/Inference-in-SmartSim.html

### ISSUE THREAD

**Issue by Wenke-D** [CrayLabs/SmartSim#779]
There is a typo in the comments of code block 9

```py
# put the PyTorch CNN in the database in GPU memory
client.set_model("cnn", traced_cnn, "TORCH", device="CPU")
```

in the GPU memory should be in **CPU** memory according to the code.

BTW, the documentation is quiet nice and clear for beginners

**Comment by al-rigazzi** [comment]
This was addressed in #780, although it will take some time to see this reflected in the docs. Thanks @Wenke-D for taking the time to file the issue!

The fix is already in the `develop` version of the docs: https://www.craylabs.org/develop/tutorials/ml_inference/Inference-in-SmartSim.html
